steps:
- task: PowerShell@1
  displayName: 'Install Unity'
  inputs:
    scriptName: ./scripts/build.ps1
    arguments: '-Target="Install-Unity-Windows" -Verbosity="Diagnostic"'

- task: PowerShell@1
  displayName: 'Activate Unity'
  inputs:
    scriptName: ./scripts/build.ps1
    arguments: '-Target="RegisterUnity" -UnitySerialNumber="$(UNITY_SERIAL_NUMBER)" -UnityUsername="$(UNITY_USERNAME)" -UnityPassword="$(UNITY_PASSWORD)" -Verbosity="Diagnostic"'

- script: |
   echo After activating unity, some important .meta files are deleted, so they must be un-deleted
   git config --global user.email "you@example.com"
   git config --global user.name "Your Name"
   git stash
  displayName: 'git stash'

- task: PowerShell@1
  displayName: 'Download Android NDK'
  inputs:
    scriptName:  ./scripts/build.ps1
    arguments: '-Target="DownloadNdk" -NdkUrl="$(ANDROID_NDK_URL)" -Verbosity="Diagnostic"'

- task: PowerShell@1
  displayName: 'Build Puppet Apps'
  inputs:
    scriptName: ./scripts/build.ps1
    arguments: '-Target="BuildApp" -Verbosity="Diagnostic"'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'MyArtifact'
    targetPath: './CAKE_SCRIPT_TEMPMyUnityAppBuilds/'
    
- task: PowerShell@1
  displayName: 'Unregister Unity'
  inputs:
    scriptName: ./scripts/build.ps1
    arguments: '-Target="UnregisterUnity" -Verbosity="Diagnostic"'
  condition: always()