steps:
- task: ShellScript@2
  displayName: 'Install Unity'
  inputs:
    scriptPath: 'scripts/install-unity.sh'

- task: ShellScript@2
  displayName: 'Activate Unity'
  inputs:
    scriptPath: ./scripts/build.sh
    args: '-target=RegisterUnity -UnitySerialNumber="$(UNITY_SERIAL_NUMBER_MACOS)" -UnityUsername="$(UNITY_USERNAME)" -UnityPassword="$(UNITY_PASSWORD)" -Verbosity="Diagnostic"'

- task: tsuyoshiushio.shell-exec.shellexec.shellexec@0
  displayName: 'git stash'
  inputs:
    code: |
     # After activating unity, some important .meta files are deleted, so they must be un-deleted
     git stash
     
- task: ShellScript@2
  displayName: 'Download Android NDK'
  inputs:
    scriptPath: ./scripts/build.sh
    args: '-target=DownloadNdk -NdkUrl="$(ANDROID_NDK_URL)" -Verbosity="Diagnostic"'

- task: ShellScript@2
  displayName: 'Run Cake Target "BuildApp"'
  inputs:
    scriptPath: ./scripts/build.sh
    args: '-target=BuildApp -Verbosity="Diagnostic"'


- task: ShellScript@2
  displayName: 'Unregister Unity'
  inputs:
    scriptPath: ./scripts/build.sh
    args: '-target=UnregisterUnity -Verbosity="Diagnostic"'

  condition: always()